import { describe, it, expect, vi } from 'vitest';
import { LlmGateway, ProviderRegistry, PromptCache, QuotaManager, QuotaExceededError } from '@nexa/llm';
import { LlmProvider, LlmRequest, LlmResponse } from '@nexa/llm';

describe('E2E: LLM Gateway (Cascade & Cache)', () => {
  it('cascades to fallback provider when primary provider throws QuotaExceededError', async () => {
    const registry = new ProviderRegistry();
    const cache = new PromptCache();
    const quota = new QuotaManager();

    // Mock Primary: Always throws QuotaExceededError
    const mockPrimary: LlmProvider = {
      name: 'groq',
      models: { OUTREACH_EMAIL: 'primary-model' },
      rateLimit: { requestsPerMinute: 10, requestsPerDay: 100 },
      costPerMillionTokens: { input: 0, output: 0 },
      isAvailable: async () => true,
      getRemainingQuota: async () => ({ remainingMinute: 0, remainingDay: 0, isAvailable: false }),
      getHealthStatus: async () => ({ name: 'groq', status: 'HEALTHY', latencyMs: 5, checkedAt: new Date() }),
      complete: async () => {
        throw new QuotaExceededError('groq', 'Minute rate limit reached');
      }
    };

    // Mock Fallback: Responds successfully
    const mockFallback: LlmProvider = {
      name: 'openrouter',
      models: { OUTREACH_EMAIL: 'fallback-model' },
      rateLimit: { requestsPerMinute: 10, requestsPerDay: 100 },
      costPerMillionTokens: { input: 0, output: 0 },
      isAvailable: async () => true,
      getRemainingQuota: async () => ({ remainingMinute: 50, remainingDay: 500, isAvailable: true }),
      getHealthStatus: async () => ({ name: 'openrouter', status: 'HEALTHY', latencyMs: 10, checkedAt: new Date() }),
      complete: async (req: LlmRequest): Promise<LlmResponse> => ({
        content: 'Fallback outreach generated successfully by OpenRouter.',
        provider: 'openrouter',
        model: 'fallback-model',
        taskType: req.taskType,
        usage: { promptTokens: 20, completionTokens: 40, totalTokens: 60 },
        cached: false,
        cost: 0,
        latencyMs: 12
      })
    };

    registry.register('groq', mockPrimary);
    registry.register('openrouter', mockFallback);

    const gateway = new LlmGateway(registry, cache, quota);

    const result = await gateway.complete({
      taskType: 'OUTREACH_EMAIL',
      prompt: 'Write an outreach email for Lead Systems Engineer'
    });

    expect(result).toBeDefined();
    expect(result.provider).toBe('openrouter');
    expect(result.content).toContain('Fallback outreach');
  });

  it('serves cached response on second identical request with zero extra LLM calls', async () => {
    const registry = new ProviderRegistry();
    const cache = new PromptCache();
    const quota = new QuotaManager();

    let completionCalls = 0;
    const trackingProvider: LlmProvider = {
      name: 'groq',
      models: { OUTREACH_EMAIL: 'groq-model' },
      rateLimit: { requestsPerMinute: 30, requestsPerDay: 1000 },
      costPerMillionTokens: { input: 0, output: 0 },
      isAvailable: async () => true,
      getRemainingQuota: async () => ({ remainingMinute: 100, remainingDay: 1000, isAvailable: true }),
      getHealthStatus: async () => ({ name: 'groq', status: 'HEALTHY', latencyMs: 5, checkedAt: new Date() }),
      complete: async (req: LlmRequest): Promise<LlmResponse> => {
        completionCalls++;
        return {
          content: 'Outreach email content generated by provider.',
          provider: 'groq',
          model: 'groq-model',
          taskType: req.taskType,
          usage: { promptTokens: 30, completionTokens: 50, totalTokens: 80 },
          cached: false,
          cost: 0,
          latencyMs: 15
        };
      }
    };

    registry.register('groq', trackingProvider);
    const gateway = new LlmGateway(registry, cache, quota);

    const promptText = 'Identical prompt for caching test';

    // 1st request -> calls provider
    const res1 = await gateway.complete({
      taskType: 'OUTREACH_EMAIL',
      prompt: promptText
    });
    expect(res1.cached).toBe(false);
    expect(completionCalls).toBe(1);

    // 2nd request with same prompt -> hits cache
    const res2 = await gateway.complete({
      taskType: 'OUTREACH_EMAIL',
      prompt: promptText
    });
    expect(res2.cached).toBe(true);
    expect(res2.content).toBe(res1.content);
    // Completion count remains 1!
    expect(completionCalls).toBe(1);
  });
});
